# Generated by tools/update_toolchain_versions.sh.
# Edit the generator inputs rather than this file.

GO_JSONNET_DEFAULT_VERSION = "0.22.0"
JRSONNET_DEFAULT_VERSION = "0.5.0-pre98"
JSONNET_DEFAULT_VERSION = "0.22.0"

GO_JSONNET_TOOLCHAINS = {
    "0.22.0": {
        "darwin_amd64": {
            "archive": True,
            "binary": "jsonnet",
            "sha256": "2ada40ece13e8b4e1f37c06315783110c84b496963b0b8b90809daf69df7dfc9",
            "url": "https://github.com/google/go-jsonnet/releases/download/v0.22.0/go-jsonnet_0.22.0_darwin_amd64.tar.gz",
        },
        "darwin_arm64": {
            "archive": True,
            "binary": "jsonnet",
            "sha256": "112534191b6e27f2ae01bb80c6ab82950fb7bf5772e2e81c5472f59a069700f5",
            "url": "https://github.com/google/go-jsonnet/releases/download/v0.22.0/go-jsonnet_0.22.0_darwin_arm64.tar.gz",
        },
        "linux_amd64": {
            "archive": True,
            "binary": "jsonnet",
            "sha256": "e87a93ea44e34da92c15636205c7f2240bf3ac92d00ccb855dbb4e7e03ea6941",
            "url": "https://github.com/google/go-jsonnet/releases/download/v0.22.0/go-jsonnet_0.22.0_linux_amd64.tar.gz",
        },
        "linux_arm64": {
            "archive": True,
            "binary": "jsonnet",
            "sha256": "3016b049254cb92548ba99304b6f44ec3795e6173f908e3ce3c5add57243fe20",
            "url": "https://github.com/google/go-jsonnet/releases/download/v0.22.0/go-jsonnet_0.22.0_linux_arm64.tar.gz",
        },
    },
}

JRSONNET_TOOLCHAINS = {
    "0.5.0-pre98": {
        "aarch64-darwin": {
            "binary": "jsonnet",
            "sha256": "c38f97e6a5bd85d3a77b7f638501111ced0d04c12208318759018ff921748e84",
            "url": "https://github.com/deltarocks/jrsonnet/releases/download/v0.5.0-pre98/jrsonnet-aarch64-darwin",
        },
        "aarch64-linux-musl": {
            "binary": "jsonnet",
            "sha256": "3dfa379d57bf1d9a33e4ec5f12878b84ccf5fc3bc80cfda202a9723ae6f7ea28",
            "url": "https://github.com/deltarocks/jrsonnet/releases/download/v0.5.0-pre98/jrsonnet-aarch64-linux-musl",
        },
        "x86_64-linux-musl": {
            "binary": "jsonnet",
            "sha256": "63d4ca485c950a52164d7e2c55763af1a24416c38c2b708aa2bca27a1e17846a",
            "url": "https://github.com/deltarocks/jrsonnet/releases/download/v0.5.0-pre98/jrsonnet-x86_64-linux-musl",
        },
    },
}

JSONNET_TOOLCHAINS = {
    "0.22.0": {
    },
}

