#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output="${repo_root}/jsonnet/version.bzl"

go_jsonnet_version="${GO_JSONNET_VERSION:-0.22.0}"
jrsonnet_version="${JRSONNET_VERSION:-0.5.0-pre98}"
jsonnet_version="${JSONNET_VERSION:-0.22.0}"

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

github_api() {
  local repo="$1"
  local version="$2"
  curl -fsSL "https://api.github.com/repos/${repo}/releases/tags/v${version}"
}

starlark_map() {
  local name="$1"
  local version="$2"
  local json="$3"

  printf '%s = {\n' "$name"
  printf '    "%s": {\n' "$version"
  jq -r '
    to_entries[] |
    "        \"\(.key)\": {\n" +
    (if .value.archive then "            \"archive\": True,\n" else "" end) +
    "            \"binary\": \"\(.value.binary)\",\n" +
    "            \"sha256\": \"\(.value.sha256)\",\n" +
    "            \"url\": \"\(.value.url)\",\n" +
    "        },"
  ' <<<"${json}"
  printf '    },\n'
  printf '}\n\n'
}

go_jsonnet_assets() {
  github_api "google/go-jsonnet" "$go_jsonnet_version" | jq --arg version "$go_jsonnet_version" '
    def digest: .digest | sub("^sha256:"; "");
    reduce .assets[] as $asset ({};
      if $asset.name == "go-jsonnet_\($version)_darwin_amd64.tar.gz" then
        .darwin_amd64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "go-jsonnet_\($version)_darwin_arm64.tar.gz" then
        .darwin_arm64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "go-jsonnet_\($version)_linux_amd64.tar.gz" then
        .linux_amd64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "go-jsonnet_\($version)_linux_arm64.tar.gz" then
        .linux_arm64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      else
        .
      end
    )
  '
}

jrsonnet_assets() {
  github_api "deltarocks/jrsonnet" "$jrsonnet_version" | jq '
    def digest: .digest | sub("^sha256:"; "");
    reduce .assets[] as $asset ({};
      if $asset.name == "jrsonnet-aarch64-darwin" then
        .["aarch64-darwin"] = {binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "jrsonnet-aarch64-linux-musl" then
        .["aarch64-linux-musl"] = {binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "jrsonnet-x86_64-linux-musl" then
        .["x86_64-linux-musl"] = {binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      else
        .
      end
    )
  '
}

jsonnet_assets() {
  github_api "google/jsonnet" "$jsonnet_version" | jq --arg version "$jsonnet_version" '
    def digest: .digest | sub("^sha256:"; "");
    reduce .assets[] as $asset ({};
      if $asset.name == "jsonnet_\($version)_darwin_amd64.tar.gz" or $asset.name == "jsonnet-\($version)-darwin-amd64.tar.gz" then
        .darwin_amd64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "jsonnet_\($version)_darwin_arm64.tar.gz" or $asset.name == "jsonnet-\($version)-darwin-arm64.tar.gz" then
        .darwin_arm64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "jsonnet_\($version)_linux_amd64.tar.gz" or $asset.name == "jsonnet-\($version)-linux-amd64.tar.gz" then
        .linux_amd64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      elif $asset.name == "jsonnet_\($version)_linux_arm64.tar.gz" or $asset.name == "jsonnet-\($version)-linux-arm64.tar.gz" then
        .linux_arm64 = {archive: true, binary: "jsonnet", sha256: ($asset | digest), url: $asset.browser_download_url}
      else
        .
      end
    )
  '
}

require curl
require jq

go_jsonnet_json="$(go_jsonnet_assets)"
jrsonnet_json="$(jrsonnet_assets)"
jsonnet_json="$(jsonnet_assets)"

{
  printf '# Generated by tools/update_toolchain_versions.sh.\n'
  printf '# Edit the generator inputs rather than this file.\n\n'
  printf 'GO_JSONNET_DEFAULT_VERSION = "%s"\n' "$go_jsonnet_version"
  printf 'JRSONNET_DEFAULT_VERSION = "%s"\n' "$jrsonnet_version"
  printf 'JSONNET_DEFAULT_VERSION = "%s"\n\n' "$jsonnet_version"
  starlark_map "GO_JSONNET_TOOLCHAINS" "$go_jsonnet_version" "$go_jsonnet_json"
  starlark_map "JRSONNET_TOOLCHAINS" "$jrsonnet_version" "$jrsonnet_json"
  starlark_map "JSONNET_TOOLCHAINS" "$jsonnet_version" "$jsonnet_json"
} >"$output"
